First branch for my portfolio project.
Amazinggracee/Portfolio pull request #1
Opened 2023-02-14 19:46 UTC by Amazinggracee

- [ ] I made sure that there are no linter errors.
- [ ] I made sure that you used the correct GitHub flow.
- [ ] I made sure that you documented your work in a professional way.
- [ ] Follow our list of best practices for HTML & CSS.
- [ ] I understood how to parse a Figma design to create a UI.
- [ ] I used Flexbox to place elements on the page.
- [ ] I built a personal portfolio site.
- [ ] I used images and backgrounds to enhance the look of my website.

2023-02-14 20:34 UTC, MeqdamAlqudah reviewed
Hi @Amazinggracee , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your Pull Request should have a descriptive title telling you what changes are inside, it is not enough to say it is the first branch for your portfolio project you can put the name of the milestone such as `Portfolio: setup and mobile first`. 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-15 05:36 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @Amazinggracee, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 05:36 UTC, brainconnect93 commented on index.html
> +  </section>
- [ ] Great effort working on the mobile setup of your portfolio project, but i would like to highlight something to work on below 👇 

   - The first part that I marked red in the image is not necessarily needed in your project, because it was just given in order to indicate to the student that it's a mobile, it is not necessarily a requirement to add it,
   - Secondly, all the social media icons added to your project are broken and you should kindly fix then.
   
Your design 👇 

![Amaze](https://user-images.githubusercontent.com/78634841/218936046-e1763abc-7364-4cca-84c5-e9f11875ad99.png)

2023-02-15 07:12 UTC, PinkMoon25 requested changes
Hi @Amazinggracee , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 07:12 UTC, PinkMoon25 commented on index.html
> +        <a href=""><img src="./images/Icon - Medium.png" alt="Medium-icon" /></a>
- [ ] As requested by the previous reviewer https://github.com/Amazinggracee/Portfolio/pull/1#discussion_r1106651246 Your social links are broken and are not showing up on the page, this is because your src path is incorrect, notice that your images directory is named Images with a capital `I`, you can either modify your directory name or correct the image src path for your icons, please fix this and make sure the icons are displayed properly :pray:
currently :point_down: 
![image](https://user-images.githubusercontent.com/97521557/218957165-f471b184-8d8c-47a4-8050-0c7f7dc2c134.png)

2023-02-15 08:22 UTC, Lizdev-05 approved these changes
Hi @Amazinggracee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>
## Highlights
- [ ] linter checks ✔️
- [ ] github flow ✔️

## Optional suggestions

- [ ] I think you should reduce the navbar header so as to meet up with the figma template 😊 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/73854999/218972064-93697572-2a5b-4771-bff0-38f833772971.png">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 05:54 UTC, merged