Added the accessiblity list
Amazinggracee/Portfolio pull request #13
Opened 2022-12-20 13:18 UTC by Amazinggracee

2022-12-20 15:08 UTC, OyePriscilla requested changes
Hi @Amazinggracee and @PowerLevel9000 😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github flow observed✔️
Linters checks passed ✔️ 

## Required Changes ♻️

- [x] Please, according to the evaluation guidelines, we need to run your live demo through [this tool](https://www.aditus.io/button-contrast-checker/). Not all of the checks are passing for your project, kindly run your live demo through it and consider making all the changes suggested by the tool. ℹ️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 15:08 UTC, OyePriscilla commented on index.html
>          </div>
- [ ] Please, perhaps there is a mix up somewhere I noticed that other cards are missing in your web app, kindly implement this according to the design. 💁‍♂️ 
- [ ] Kindly don't forget to change the `h1 `tag in line 109 to any other header tag (`h2, h3 .`....), we suppose to use only `h1 `tag per page; this should represent the main heading/subject for the whole page. ℹ️ 

 ## Figma design
![figma skilss](https://user-images.githubusercontent.com/103386183/208697640-3bae65a8-69d1-489c-8a8f-7e9864b53f21.jpg)

## Your Design




![figma skilss](https://user-images.githubusercontent.com/103386183/208697814-1d6c9c33-729e-4175-a7cc-8614258d3d07.jpg)

2022-12-21 03:57 UTC, binhussen requested changes
Hi @Amazinggracee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
- Kindly use semantic tags appropriately as your previous code reviewer suggested 👌.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 03:57 UTC, binhussen commented on index.html
> +    <title>My Portfolio</title>
- Kindly Update your portfolio title to be more adequate mostly for SEO optimization as your previous code reviewer suggested 👌.

2022-12-21 03:57 UTC, binhussen commented on index.html
> +                </h1>
- Kindly change the `h1` tag to any other header tag (h2, h3 .....), we suppose to use only the `h1` tag per page; this should represent the main heading/subject for the whole page. as your previous code reviewer suggested.👌👍

2022-12-21 03:57 UTC, binhussen commented on style.css
>    align-items: center;
- [Optional] Kindly use relative as they are useful for styling responsive sites because they scale relative to the parent or window size (depending on the unit). such as `rem`, `em` etc....👍👍

2022-12-21 15:07 UTC, mukhammadrizooff approved these changes
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions
- [ ] [OPTIONAL] Good job so far! Keep it doing well job 🥇 

![image](https://user-images.githubusercontent.com/63915024/208937073-c867d75c-e7a8-4ac4-83c6-f626808e8a61.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 06:39 UTC, merged