Portfolio - mobile menu
Amazinggracee/Portfolio pull request #14
Opened 2023-01-02 15:09 UTC by Amazinggracee

- [ ] Use basic JavaScript syntax.
- [ ] Use JavaScript to manipulate DOM elements.
- [ ] Use JavaScript events.
- [ ] Make sure that there are no linter errors.
- [ ] Make sure that you used the correct GitHub flow.
- [ ] Make sure that you documented your work in a professional way.
- [ ] Follow our list of best practices for HTML & CSS.
- [ ] Follow our list of best practices for JavaScript.
- [ ] In mobile, implement the following features:
> - [ ] When the user clicks (or taps) the hamburger button, the mobile menu appears.
> - [ ] When the user clicks (or taps) the close (X) button, the mobile menu disappears.
> - [ ] When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
> - [ ] When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed.

2023-01-02 20:36 UTC, huseyinbiyik commented
Hi @Amazinggracee and @crispin12,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the sections exist in yours and placeholders are replaced with your project and personal data. The only optional section is FAQ.  Also please make sure you deleted the logo on the top unless you have your own personal logo. And please make sure you added a license and the link directing to your license works fine. This is crucial to have a professional and instructive repository.  👌
<img width="836" alt="Screenshot 2023-01-02 at 11 30 44 PM" src="https://user-images.githubusercontent.com/25887253/210276100-239958d4-6da3-4f51-9a02-1809c7a021c9.png">
<img width="836" alt="Screenshot 2023-01-02 at 11 30 51 PM" src="https://user-images.githubusercontent.com/25887253/210276101-d80b932a-ca20-451c-9609-cf98b34cde22.png">

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-02 23:11 UTC, Munsa1 requested changes
Hi @Amazinggracee, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-02 23:11 UTC, Munsa1 commented on index.html
> +    </nav>
- [ ] It could be a technical glitch but I have tried downloading this project twice and when I switch from desktop to mobile view the mobile menu does not pop up, kindly fix this issue.

Your design
![image](https://user-images.githubusercontent.com/81932478/210283647-b9a64ccb-1a06-455a-968b-69824646263c.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/210283724-f6cfa2f7-b3c2-4389-87ed-803e23f4a9a6.png)

2023-01-02 23:11 UTC, Munsa1 commented on app.js
> +}
- [ ] Once the mobile menu issue is solved kindly ensure that the menu works as expected and that each link when clicked closes the menu and takes the user to the appropriate part of the page.

![image](https://user-images.githubusercontent.com/81932478/210283975-fc37a3eb-4eda-4de8-8837-ce6c41a19714.png)

2023-01-03 09:53 UTC, prolajumokeoni approved these changes
Hi @Amazinggracee 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check inline comment_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-03 09:53 UTC, prolajumokeoni commented on style.css
> +  background-color: var(--dark);
### OPTIONAL

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 2-Menu-Mobile](https://user-images.githubusercontent.com/69638013/210333670-a1e6df38-bb30-4e96-a91a-d8fbebd37658.png)  | ![Screenshot_585](https://user-images.githubusercontent.com/69638013/210333636-ebaa389b-7e43-48a1-884a-436f536aa61b.png)


- [ ] Kindly use the same color used in the Figma design for your mobile menu background,  this will make your design look exactly like the Figma design

2023-01-03 10:12 UTC, Amazinggracee commented
Thanks for the feedback!

On Tue, 3 Jan 2023 at 10:54, Oni Olajumoke Priscilla <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @Amazinggracee <https://github.com/Amazinggracee>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - No linter errors ✅
>    - Git flow was used correctly 🚀
>    - Good design 💯
>    - Good Pr title and description 💪🏿
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
> *Check inline comment*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification @prolajumokeoni <https://github.com/prolajumokeoni>.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/Amazinggracee/Portfolio/pull/14#discussion_r1060420074>
> :
>
> >  }
>
>
>
> -#myLinks a:hover {
>
> -  color: var(--grey);
>
> -  background: var(--lightgrey);
>
> +.showMenu {
>
> +  transform: translateY(0);
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  gap: 12px;
>
> +  background-color: var(--dark);
>
>
> OPTIONAL
> Figma Design Your design
> [image: Template 2-Menu-Mobile]
> <https://user-images.githubusercontent.com/69638013/210333670-a1e6df38-bb30-4e96-a91a-d8fbebd37658.png> [image:
> Screenshot_585]
> <https://user-images.githubusercontent.com/69638013/210333636-ebaa389b-7e43-48a1-884a-436f536aa61b.png>
>
>    - Kindly use the same color used in the Figma design for your mobile
>    menu background, this will make your design look exactly like the Figma
>    design
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Amazinggracee/Portfolio/pull/14#pullrequestreview-1234301650>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZW47K7NOHAMLI6ZBY35LA3WQPZMBANCNFSM6AAAAAATO4TZ2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-03 11:22 UTC, merged