Mobile 2 is about me project
Amazinggracee/Portfolio pull request #2
Opened 2022-12-02 16:09 UTC by Amazinggracee

Understand how to parse a Figma design to create a UI.
Use Flexbox to place elements on the page.
Use CSS Grid to place elements on the page.
Build a personal portfolio site.

2022-12-02 16:39 UTC, Amazinggracee commented
I am sending my first review.

2022-12-02 17:14 UTC, Tadesse-Alemayehu requested changes
### Hi @Amazinggracee 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![EquatorialVictoriousBlackpanther-size_restricted](https://user-images.githubusercontent.com/69077061/204090500-5512fd84-cfd9-4aee-9d5d-8ee90740a92d.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 17:14 UTC, Tadesse-Alemayehu commented on index.html
> +</section>
- [ ] Although you did great making the layout as they appear on the Figma design, there are still some minor details to look for. one is your layout is overflowing to the side on a `377px screen size`,
- [ ]  The other is the `my recent work ` should be centered and the font-weight better be the same as the Figma design.
- [ ] Also, the font for the heading should be `Crete Round` and for the `p` should be `Inter`

### Figma design

![Capture2](https://user-images.githubusercontent.com/69077061/205345909-d2bc1b1c-1e30-4f1a-adc2-3c1ffb9a66a3.PNG)
### Your design
![Capture](https://user-images.githubusercontent.com/69077061/205345895-6b69e79a-93fc-499e-bb9c-2e043f49b6fc.PNG)

2022-12-02 17:14 UTC, Tadesse-Alemayehu commented on index.html
>  <section>
- [ ] Dear @Amazinggracee, I can see you have not implemented your `about me section`. Please make sure to add the about me section with all the required styles and contents before the next review. Remember since I have not reviewed this section it's going to get a review as a new one.

2022-12-03 00:46 UTC, mgmediaweb approved these changes
Hi @Amazinggracee , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved4](https://user-images.githubusercontent.com/41912912/205413904-abf74d33-5ce0-4676-a829-6213f97c97ed.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 00:49 UTC, merged