Portfolio: desktop version
Amazinggracee/Portfolio pull request #4
Opened 2023-02-22 13:01 UTC by Amazinggracee

- [ ] We used media queries in our CSS file to make my desktop version look like the template I selected (Desktop:        >=768px).
- [ ]  In order to lay out the elements on the page I used use Grid and Flexbox.
- [ ] I did not implement any functionality that requires JavaScript.
- [ ] I replicated the design as much as possible (e.g., font, colors, images, text, margins) using the info from the Figma templates.

2023-02-22 13:57 UTC, IngDavidTM requested changes
## Hi @Amazinggracee  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 13:57 UTC, IngDavidTM commented on style.css
>    height: auto;
- [ ] While you did a good job styling the `header` section :+1:, it is required to stick as much as possible to the Figma template. I mention some of the required changes below:
- Kindly make the section a little bit bigger :+1: 
- The title 'Hello I'm...' should be also bigger to match the template :+1: 
- Please make sure that the social links are aligned with the middle of the page

**Your design**

![Screenshot from 2023-02-22 08-30-58](https://user-images.githubusercontent.com/105117832/220635343-f96c9828-8dcf-4f12-83ae-d141a93f4e47.png)


**Figma**

![Screenshot from 2023-02-22 08-28-40](https://user-images.githubusercontent.com/105117832/220635243-698f654a-df88-42c7-b153-a13db63ec589.png)

2023-02-22 13:57 UTC, IngDavidTM commented on style.css
>  #works h5 {
- [ ] As mentioned before you did a good job styling the `works` section :+1:,  but as a project requirement you should stick as much as possible to the Figma template. I mention some of the required changes below:
- Kindly make sure that the elements are not overlapping between them :+1: 
- The section should be aligned to the center of the page :+1: 

**Your design**

![Screenshot from 2023-02-22 08-31-13](https://user-images.githubusercontent.com/105117832/220636807-13979bf0-179b-4ae6-b1c2-47f95fa72699.png)

**Figma**

![Screenshot from 2023-02-22 08-28-55](https://user-images.githubusercontent.com/105117832/220636899-dc4fe1d7-1fce-4817-9220-e133b3b85191.png)

2023-02-22 13:57 UTC, IngDavidTM commented on style.css
>    grid-template-rows: auto;
- [ ] As mentioned before you did a good job styling the cards inside the `works` section :+1:,  but as a project requirement you should stick as much as possible to the Figma template. I mention some of the required changes below:
- Kindly make each card a little bit bigger :+1: 
- The elements inside each card should be aligned to the end of the card not the middle :+1: 
- The gap between the cards should be less to match the template :+1: 

**Your design**

![Screenshot from 2023-02-22 08-31-30](https://user-images.githubusercontent.com/105117832/220638020-a72360bd-8150-4aea-aa9a-b3ab7cc012b6.png)

**Figma**

![Screenshot from 2023-02-22 08-29-09](https://user-images.githubusercontent.com/105117832/220638127-beeec0dd-87ee-4f53-8de9-0554c2d3200d.png)

2023-02-22 13:57 UTC, IngDavidTM commented on style.css
> +  }
- [ ] As mentioned before you did a good job styling the `about` section :+1:,  but as a project requirement you should stick as much as possible to the Figma template. I mention some of the required changes below:
- The "About me" title should be aligned with the text below :+1: 
- The bar should not overlap with the background :+1: 
- The Languages, Frameworks and Skills should be aligned to the middle and each element inside of it should also be aligned as you can see below :+1: 

**Your design**

![Screenshot from 2023-02-22 08-31-44](https://user-images.githubusercontent.com/105117832/220639724-4416c1d1-c284-4b22-a8f5-e14d0a0f5051.png)

![Screenshot from 2023-02-22 08-31-58](https://user-images.githubusercontent.com/105117832/220639756-29062923-dfb5-4f6d-a5fc-47248340e82f.png)

**Figma**

![Screenshot from 2023-02-22 08-29-44](https://user-images.githubusercontent.com/105117832/220639893-295ca71f-599a-4f47-93a3-91614f1fc23d.png)

![Screenshot from 2023-02-22 08-29-57](https://user-images.githubusercontent.com/105117832/220639946-8d625a4f-a7cf-4b10-987c-f0504646bd18.png)

2023-02-22 13:57 UTC, IngDavidTM commented on style.css
> +  }
- [ ] As mentioned before you did a good job styling the `contact` section :+1:,  but as a project requirement you should stick as much as possible to the Figma template. I mention some of the required changes below:
- The title should be bigger :+1: 
- The elements should be aligned to the middle of the page as you can see below :+1: 


**Your design**

![Screenshot from 2023-02-22 08-32-11](https://user-images.githubusercontent.com/105117832/220640845-8a56a040-9ca7-4570-88e7-5838a4a5d6a1.png)

**Figma**

![Screenshot from 2023-02-22 08-30-10](https://user-images.githubusercontent.com/105117832/220640918-0b3907cc-4cd8-4c9b-9f8c-2bb86ff6176e.png)

2023-02-22 23:36 UTC, souad988 requested changes
Hi @Amazinggracee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/220787900-8a6b2d09-dd69-4b75-9c44-dc35e43d0da5.gif)


## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 23:36 UTC, souad988 commented on style.css
>    height: auto;
well done @Amazinggracee  on this project , but this section still needs small changes to be as close as possible to figma desing as requested by the previous reviewer 
the title doesn't have the same font size and I suggest that you use relative units like rem to make your text also scale with screen size.

**figma headline section**
![figma template2 desktop headline](https://user-images.githubusercontent.com/59707859/220784502-51c8a41d-4ad9-439c-80dd-e1de94b84272.PNG)

**your headline section**
![student template2 desktop headline](https://user-images.githubusercontent.com/59707859/220784563-c47f12bd-e552-46d1-bc37-765c953e3d18.PNG)


also social media section should keep centered when changing screen size to fix this issue all you need to use is justify-content: center as its flexbox and has vertical direction and don't use margin-top with pixels as this won't scale

2023-02-22 23:36 UTC, souad988 commented on style.css
>  #works h5 {
well done on fixing the overlap issue , but this section still need few changes to get perfect please pay attention to the spacing between the element all elements in this section should have the same left and right margin , I suggest that you use only one section as the content here is semantically same  so projects are meant to be inside works section 

**figma**

![space figma](https://user-images.githubusercontent.com/59707859/220787549-c9a41a21-3a27-4fa3-85a8-4c9d9c5d7045.PNG)

**your project**
![scale](https://user-images.githubusercontent.com/59707859/220787602-4ee07074-8d99-4c17-ad61-bf91b580443d.PNG)

2023-02-23 08:47 UTC, Amazinggracee commented
Good morning.
Please help me check if the design is okay now. Here is the link
https://github.com/Amazinggracee/Portfolio/pull/4

On Thu, 23 Feb 2023 at 00:37, Souad El Mansouri ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Amazinggracee <https://github.com/Amazinggracee> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: 212385281-4797c58a-d358-423a-aa7c-832c22203865]
> <https://user-images.githubusercontent.com/59707859/220787900-8a6b2d09-dd69-4b75-9c44-dc35e43d0da5.gif>
> Highlights Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/Amazinggracee/Portfolio/pull/4#discussion_r1115083144>
> :
>
> >  #intro {
>
> -  display: flex;
>
> -  flex-direction: column;
>
> -  align-items: flex-start;
>
>    padding: 120px 24px;
>
> -  gap: 12px;
>
>    position: absolute;
>
>    width: 100%;
>
>    height: auto;
>
>
> well done @Amazinggracee <https://github.com/Amazinggracee> on this
> project , but this section still needs small changes to be as close as
> possible to figma desing as requested by the previous reviewer
> the title doesn't have the same font size and I suggest that you use
> relative units like rem to make your text also scale with screen size.
>
> *figma headline section*
> [image: figma template2 desktop headline]
> <https://user-images.githubusercontent.com/59707859/220784502-51c8a41d-4ad9-439c-80dd-e1de94b84272.PNG>
>
> *your headline section*
> [image: student template2 desktop headline]
> <https://user-images.githubusercontent.com/59707859/220784563-c47f12bd-e552-46d1-bc37-765c953e3d18.PNG>
>
> also social media section should keep centered when changing screen size
> to fix this issue all you need to use is justify-content: center as its
> flexbox and has vertical direction and don't use margin-top with pixels as
> this won't scale
> ------------------------------
>
> In style.css
> <https://github.com/Amazinggracee/Portfolio/pull/4#discussion_r1115098347>
> :
>
> > -.worksDiv .line {
>
> -  position: absolute;
>
> -  top: 24%;
>
> -  height: 1.2px;
>
> -  width: 70%;
>
> -  margin-left: 5%;
>
> -}
>
> -
>
> -#works .real {
>
> -  background-image: url(./Images/Img\ Placeholder.png);
>
> -  background-repeat: no-repeat;
>
> -  background-size: 100%;
>
> -  width: 80%;
>
> -  height: 237px;
>
> -  margin-left: 5%;
>
> +#works .worksDiv img {
>
> +  display: none;
>
>  }
>
>
>
>  #works h5 {
>
>
> well done on fixing the overlap issue , but this section still need few
> changes to get perfect please pay attention to the spacing between the
> element all elements in this section should have the same left and right
> margin , I suggest that you use only one section as the content here is
> semantically same so projects are meant to be inside works section
>
> *figma*
>
> [image: space figma]
> <https://user-images.githubusercontent.com/59707859/220787549-c9a41a21-3a27-4fa3-85a8-4c9d9c5d7045.PNG>
>
> *your project*
> [image: scale]
> <https://user-images.githubusercontent.com/59707859/220787602-4ee07074-8d99-4c17-ad61-bf91b580443d.PNG>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Amazinggracee/Portfolio/pull/4#pullrequestreview-1310417823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZW47KYNGCHQNIBIVVKHAKLWY2PKNANCNFSM6AAAAAAVEJYJFE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-23 09:35 UTC, medaminedev66 commented
Hello @Amazinggracee  👋,

_This is an additional review as a result of the second opinion request._

I think all the changes requested by @souad988 are clear and easy to understand. If you see that you have implemented all the requested changes, kindly request a new review on your dashboard.

If something specific is not obvious, kindly leave a comment outlining what you did not understand so that we can explain it in more detail. Please remember to tag @souad988 or me in your comment.

Keep rocking 🚀!

2023-02-24 10:27 UTC, DuaneDave requested changes
Hi @Amazinggracee 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
✔️  Correct usage of GitHub Flow
✔️  PR title and description are professional and descriptive
✔️  All linter checks are passing


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 10:27 UTC, DuaneDave commented on index.html
> +        you need coded, don’t hestiate to contact me.
Good job extending the height of the headline section but the changes that have been made still doesn't match up with what was previously requested and they have also introduced new issues. Some unnecessary margins on the right, the texts are looking bigger than the Figma template's and also the spaces between the texts have become a little messy.

SEE THE REGIONS THAT ARE MARKED

![noFix](https://user-images.githubusercontent.com/84930355/221150059-9ec103a0-e5ce-4fd0-899e-ef0cff83dac4.PNG)


FIGMA DESIGN

![see](https://user-images.githubusercontent.com/84930355/221150280-d8d62edb-6996-4cf0-a00c-c024c0e79847.png)


I recommend that you fix this to have a UI that is very appealing and matches the Figma template.

2023-02-24 10:27 UTC, DuaneDave commented on style.css
> -  background-size: 100%;
As previously requested, I still feel the spacing between each individual card can still be improved to make it match the provided template and to make the UI much better.

Instead of using `gap: 20px 5px` in the #mobProjects class on the media query, consider using `gap: 1rem;`

YOUR DESIGN

![GAAAAPS](https://user-images.githubusercontent.com/84930355/221153781-468a34c9-55c1-4b9b-b678-e729c5fd5102.PNG)


FIGMA

![gaaaap](https://user-images.githubusercontent.com/84930355/221153936-8b0c5be7-2c04-4ef3-956d-767a5751bff3.png)

2023-02-24 18:34 UTC, adel-gu approved these changes
# Status: APPROVED 🟢🥳 

**Hi @Amazinggracee & @tsheporamantso 👋🏼** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Well-descriptive PR summary ✔️ 

## To Improve 🚀 

- [ ] Sorry this wasn't mentioned by the previous reviewers and it's not a required change but I highly recommend naming your branch to reflect a feature name or an action such as `portfolio-desktop-version` or `implement-desktop-version`...etc 💪🏼.


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 18:34 UTC, adel-gu commented on style.css
> +    margin-top: 148px;
- **[OPTIONAL]**  Well done implementing the changes asked by the previous reviewer 💪🏼, your project looks good now 😎.

However, the active project card in the project section looks slightly unaligned with the other cards 

### Your Design 
![image](https://user-images.githubusercontent.com/68030297/221259861-e0202de7-d4c9-41b5-951a-9bced1a23df8.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/221260163-0a293cb1-68d8-4879-a755-34f4fff88b87.png)


- what worked for me so you could give it a try is explained in the line below:

```css
.projectD .project {
    margin-top: 140px;
    ...
  } 
```

**_NOTE:_** I highly recommend following the [Learn CSS Grid the easy way](https://www.youtube.com/watch?v=rg7Fvvl3taU&t=836s) so you would have a solid foundation on CSS grid system 👍🏼

2023-02-24 18:46 UTC, adel-gu commented on style.css
> +  margin-left: 10px;
- [OPTIONAL] Please try working on the text area background color and ensure to stick to the Figma design 

### Your Design
![image](https://user-images.githubusercontent.com/68030297/221265512-d62cbaca-88ae-48d4-84fd-61d31cdc3feb.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/221265147-2f18908e-86dc-48aa-b9aa-da1794e93416.png)

2023-02-24 18:53 UTC, adel-gu commented on style.css
> +  }
- [OPTIONAL] Please stick to the design as much as possible, the title size in the design is much more large and it's layout is aligned at the start of the contact section.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/221266424-5349339f-eebe-40e0-b165-c9fefd550e69.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/221266909-1f1ef151-82ee-4fb1-8955-5f274c79b6cf.png)

2023-02-24 18:56 UTC, merged