We added the Desktop version, Pad example ipad mini version and mobil…
Amazinggracee/Portfolio pull request #5
Opened 2022-12-16 06:32 UTC by Amazinggracee

…e version

2022-12-16 15:00 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @Amazinggracee 
I'm sure you put a lot of effort into this project but this PR is invalid because your pull request doesn't look professional 😓 kindly write a short title like "Portfolio: desktop version" then in the description you can go on about the details of what has been done in the branch 👍 

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 16:29 UTC, huseyinbiyik commented
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 
![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Kindly fix the description title of your Pull Request. It needs to be concise and short. "Portfolio: desktop version" is good one  ↓
<img width="1056" alt="Screenshot 2022-12-16 at 7 22 28 PM" src="https://user-images.githubusercontent.com/25887253/208143644-b1eee1e0-b1a6-459e-84ec-3f2fea66a4aa.png">

- Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the sections exist in yours and placeholders are replaced with your project and personal data. Only optional section is FAQ.  This is crucial to have a professional and instructive repository. 👌

-  Please make sure your commit messages are meaningful and descriptive for your **next** commits. Use imperative tense and capitalize the first word. For example, "Add logo to navigation bar". This is crucial for a professional repository and it will help you to keep the history of your project and take the necessary actions of true points in the project history. ↓❌
<img width="791" alt="Screenshot 2022-12-16 at 7 26 15 PM" src="https://user-images.githubusercontent.com/25887253/208143943-7e4e5903-4d12-48c5-b531-f33936946a16.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-16 20:29 UTC, jerryowusu requested changes
Hi @Amazinggracee , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so-close](https://user-images.githubusercontent.com/65233860/208183765-527b30e7-9de5-4fa6-a95c-b1d65d5d3f28.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Neat and well organised code :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 20:29 UTC, jerryowusu commented on style.css
> +}
Kindly consider making your desktop page more responsive so that all parts of the pages are displayed at all screen widths. Parts of the `Recent Works` dissappears when you increase the width of the screen as shown below :point_down: 

Your design 

![Screenshot from 2022-12-16 19-57-20](https://user-images.githubusercontent.com/65233860/208179858-3a8cf1d9-aa9d-4d0d-8961-3bcbd624fd54.png)


Figma design 

![Screenshot from 2022-12-16 19-57-29](https://user-images.githubusercontent.com/65233860/208179881-8ca4a82b-d9b0-43ab-9bec-ac2720946135.png)

2022-12-16 20:29 UTC, jerryowusu commented on style.css
> +  }
kindly ensure that all parts of your website looks like the design at all screen sizes of the desktop version. Currently, there are some differences. For instance, parts of the skills section dissappears at certain screen widths as shown below. :point_down: Kindly check and fix it. :+1: 

## Your design

![Screenshot from 2022-12-16 19-58-23](https://user-images.githubusercontent.com/65233860/208181352-2853a0df-ec30-4513-aaba-dc1abbea6c3c.png)


## figma design 

![Screenshot from 2022-12-16 19-58-34](https://user-images.githubusercontent.com/65233860/208181371-238b3a93-06ee-477a-98d9-83675cb81027.png)

2022-12-16 20:29 UTC, jerryowusu commented on style.css
> +  }
Kindly pay close attention to the layout and dimensions of the contact form. Check the position of the last name as well as the button. Please make sure they conform to the figma design

## Your design 

![Screenshot from 2022-12-16 19-59-01](https://user-images.githubusercontent.com/65233860/208182307-5fc84bfe-4ea4-4133-a99a-c3c44a269964.png)

## Figma design


![Screenshot from 2022-12-16 19-58-51](https://user-images.githubusercontent.com/65233860/208182377-cd735122-930e-4d29-a5bf-ffa3f919de1e.png)

2022-12-16 20:29 UTC, jerryowusu commented on style.css
> +  margin-left: 20px;
Kindly check the text alignment and font-size of the contact paragraph and ensure it conforms to the figma design. There seems to  be some disparities as shown below. :point_down: 

## Your design 

![Screenshot from 2022-12-16 19-59-08](https://user-images.githubusercontent.com/65233860/208183379-c68f4c61-6708-4e2a-a665-054cf80b7e06.png)


## Figma design 

![Screenshot from 2022-12-16 19-59-15](https://user-images.githubusercontent.com/65233860/208183369-7bcc49ca-9bb5-4588-ba29-b4f2c7084502.png)

2022-12-17 04:30 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Amazinggracee , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is incomplete!  There are issues you still need to address, but for this part of the milestone, it would be approved... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
***Check the comment under the reviews*** :exclamation: :exclamation: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 04:30 UTC, zieeco commented on style.css
> +}
**[OPTIONAL FOR NOW]** :exclamation: :exclamation: 

- Hey, Your work section is looking very different from the Figma template. As the previous reviewer didn't point it, it's marked optional for now but in your next milestone, it won't be marked optional. Please, kindly compare your cards in the work's sections with Figma to improve your design. See your card design below and check the cards in the Figma design:




![Screenshot from 2022-12-17 05-07-30](https://user-images.githubusercontent.com/59397159/208224678-1e462ffa-2b85-4fe3-afd6-a02b51eaa55c.png)
![Screenshot from 2022-12-17 05-07-40](https://user-images.githubusercontent.com/59397159/208224676-170f3735-15b0-4be5-8fb9-20c78d761336.png)
![Screenshot from 2022-12-17 05-07-52](https://user-images.githubusercontent.com/59397159/208224673-27e9c471-c5bd-425f-aa0a-cbd3dc6b17b6.png)

2022-12-17 08:13 UTC, closed without merging